[package]
name = "collections"
version = "0.1.0"
authors = ["Daniel Sedlak <daniel@sedlak.biz>"]
edition = "2018"
description = "Implementation of common collections"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
